import os 

## DEFIND TASK TRAINING

EMBEDDING_RANKER_NUMERICAL= "label_is_numerical"
EMBEDDING_CONTRASTIVE= "label_is_other_embedding"
EMBEDDING_TRIPLET= "label_is_pos_neg"
EMBEDDING_IN_BATCH_NEGATIVES= "multi_negatives"


## DEFIND LOSSES FOR TRAINING EMBEDDING AND RANKER MODEL

BINARY_CROSS_ENTROPY_LOSS= "binary_crossentropy"
CATEGORICAL_CROSS_ENTROPY_LOSS= "categorical_crossentropy"
MSE_LOGARIT= "mselog"
COSINE_SIMILARITY_LOSS= "cosine_similarity"
CONSTRASTIVE_LOSS= "contrastive"
TRIPLET_LOSS="triplet"
IN_BATCH_NEGATIVES_LOSS= "in_batch_negatives"


## DEFIND RULE_LOSS_TASK
RULE_LOSS_TASK= { 
    BINARY_CROSS_ENTROPY_LOSS: EMBEDDING_RANKER_NUMERICAL, 
    CATEGORICAL_CROSS_ENTROPY_LOSS: EMBEDDING_RANKER_NUMERICAL, 
    MSE_LOGARIT: EMBEDDING_RANKER_NUMERICAL, 
    COSINE_SIMILARITY_LOSS: EMBEDDING_RANKER_NUMERICAL, 
    CONSTRASTIVE_LOSS: EMBEDDING_CONTRASTIVE, 
    TRIPLET_LOSS: EMBEDDING_TRIPLET, 
    IN_BATCH_NEGATIVES_LOSS: EMBEDDING_IN_BATCH_NEGATIVES
}

RESPONSE_RULE= os.path.join(os.path.dirname(__file__), "utils/rule_response/response_rule.yml")